version: '3'

tasks:
  default:
    desc: Run the complete analysis pipeline
    deps: [render]
    cmds:
      - task: run

  render:
    desc: Render the targets Rmarkdown document
    sources:
      - _targets.Rmd
      - R/**/*.R
    generates:
      - _targets.md
    cmds:
      - echo "Rendering _targets.Rmd..."
      - Rscript -e "rmarkdown::render('_targets.Rmd')"

  run:
    desc: Run the targets pipeline
    sources:
      - _targets.R
      - R/**/*.R
      - _targets_r/**/*.R
    cmds:
      - echo "Running targets pipeline..."
      - Rscript -e "targets::tar_make()"

  visualize:
    desc: Create a visualization of the pipeline
    deps: [render]
    cmds:
      - echo "🔍 Creating pipeline visualization..."
      - |
        Rscript -e '
        if (!requireNamespace("visNetwork", quietly = TRUE)) {
          stop("The visNetwork package is required. Run: task install-deps")
        }
        targets::tar_visnetwork()
        message("✅ Pipeline visualization opened in browser")
        '

  progress:
    desc: Show pipeline progress
    cmds:
      - echo "Checking pipeline progress..."
      - Rscript -e "targets::tar_progress()"

  clean:
    desc: Clean targets cache (use with caution!)
    interactive: true
    cmds:
      - |
        echo "⚠️  WARNING: This will delete all computed results in _targets/"
        echo "   This action cannot be undone."
        echo ""
        printf "   Are you sure you want to continue? [y/N] "
        read -r REPLY
        if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
          echo "🗑️  Removing _targets/ directory..."
          rm -rf _targets/
          echo "✅ Targets cache cleaned successfully"
        else
          echo "❌ Clean operation cancelled"
        fi

  help:
    desc: Show available commands
    cmds:
      - task --list

  install:
    desc: Install required R packages
    cmds:
      - echo "📦 Installing R packages..."
      - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv', repos = 'https://cloud.r-project.org')"
      - Rscript -e "if (file.exists('renv.lock')) renv::restore() else message('No renv.lock file found. Skipping restore.')"
      - echo "✅ Package installation complete"

  install-deps:
    desc: Install all dependencies needed for the analysis
    cmds:
      - echo "📦 Installing project dependencies..."
      - |
        Rscript -e '
        repos <- "https://cloud.r-project.org"
        pkgs <- c("targets", "tarchetypes", "data.table", "ggplot2", "patchwork", 
                  "purrr", "here", "dplyr", "tidyr", "qs", "qs2", "crew", 
                  "primarycensored", "cmdstanr", "fitdistrplus", "profvis", 
                  "rmarkdown", "knitr", "visNetwork")
        
        # Install missing packages
        missing <- pkgs[!pkgs %in% installed.packages()[,"Package"]]
        if (length(missing) > 0) {
          message("Installing: ", paste(missing, collapse = ", "))
          install.packages(missing, repos = repos)
        } else {
          message("All required packages are already installed")
        }
        
        # Special handling for cmdstanr (needs cmdstan)
        if ("cmdstanr" %in% pkgs && !cmdstanr::cmdstan_version()) {
          message("Installing CmdStan...")
          cmdstanr::install_cmdstan()
        }
        '
      - echo "✅ All dependencies installed successfully"

  profile:
    desc: Profile the targets pipeline with profvis to identify bottlenecks
    cmds:
      - echo "Profiling targets pipeline with profvis..."
      - Rscript -e "library(profvis); results <- profvis(targets::tar_make(callr_function = NULL, use_crew = FALSE, as_job = FALSE)); saveRDS(results, 'profile_results.rds'); print(results, aggregate = TRUE)"
      - echo "Profile results saved to profile_results.rds"

  profile-proffer:
    desc: Profile the targets pipeline with proffer
    cmds:
      - echo "Profiling targets pipeline with proffer..."
      - Rscript -e "if (!requireNamespace('proffer', quietly = TRUE)) install.packages('proffer'); proffer::pprof(targets::tar_make(callr_function = NULL, use_crew = FALSE, as_job = FALSE))"