version: '3'

tasks:
  default:
    desc: Run the complete analysis pipeline
    deps: [install, render]
    cmds:
      - task: run

  render:
    desc: Render the targets Rmarkdown document
    sources:
      - _targets.Rmd
      - R/**/*.R
    generates:
      - _targets.md
    cmds:
      - echo "Rendering _targets.Rmd..."
      - Rscript -e "rmarkdown::render('_targets.Rmd')"

  run:
    desc: Run the targets pipeline
    sources:
      - _targets.R
      - R/**/*.R
      - _targets_r/**/*.R
    cmds:
      - echo "Running targets pipeline..."
      - Rscript -e "targets::tar_make()"

  visualize:
    desc: Create a visualization of the pipeline
    deps: [render]
    cmds:
      - echo "🔍 Creating pipeline visualization..."
      - |
        Rscript -e '
        if (!requireNamespace("visNetwork", quietly = TRUE)) {
          stop("The visNetwork package is required. Run: task install-deps")
        }
        
        # Create interactive visualization
        vis <- targets::tar_visnetwork()
        
        # Save as HTML
        htmlwidgets::saveWidget(
          vis, 
          "pipeline_visualization.html", 
          selfcontained = TRUE
        )
        
        message("✅ Pipeline visualization opened in browser")
        message("   - HTML saved to: pipeline_visualization.html")
        message("   - To convert to image, use: task visualize-png")
        '

  visualize-png:
    desc: Convert pipeline visualization to PNG image
    deps: [visualize]
    cmds:
      - echo "📸 Converting pipeline visualization to PNG..."
      - |
        Rscript -e '
        if (!requireNamespace("webshot2", quietly = TRUE)) {
          stop("The webshot2 package is required. Run: task install-deps")
        }
        
        # Check if HTML exists
        if (!file.exists("pipeline_visualization.html")) {
          stop("No HTML visualization found. Run: task visualize")
        }
        
        # Convert HTML to PNG
        webshot2::webshot(
          "pipeline_visualization.html",
          "pipeline_visualization.png",
          vwidth = 1200,
          vheight = 800,
          zoom = 2
        )
        
        message("✅ Pipeline visualization saved as PNG")
        message("   - Image saved to: pipeline_visualization.png")
        '

  progress:
    desc: Show pipeline progress
    cmds:
      - echo "Checking pipeline progress..."
      - Rscript -e "targets::tar_progress()"

  clean:
    desc: Clean targets cache (use with caution!)
    interactive: true
    cmds:
      - |
        echo "⚠️  WARNING: This will delete all computed results in _targets/"
        echo "   This action cannot be undone."
        echo ""
        printf "   Are you sure you want to continue? [y/N] "
        read -r REPLY
        if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
          echo "🗑️  Removing _targets/ directory..."
          rm -rf _targets/
          echo "✅ Targets cache cleaned successfully"
        else
          echo "❌ Clean operation cancelled"
        fi

  help:
    desc: Show available commands
    cmds:
      - task --list

  renv-init:
    desc: Initialize renv for dependency management
    cmds:
      - echo "🔧 Initializing renv..."
      - |
        Rscript -e '
        if (!requireNamespace("renv", quietly = TRUE)) {
          install.packages("renv", repos = "https://cloud.r-project.org")
        }
        
        # Initialize renv if not already done
        if (!file.exists("renv.lock")) {
          renv::init(bare = TRUE)
          message("renv initialized. Use task install to add packages.")
        } else {
          message("renv already initialized.")
        }
        '

  install:
    desc: Install/restore R packages using renv
    deps: [renv-init]
    cmds:
      - echo "📦 Managing R packages with renv..."
      - |
        Rscript -e '
        if (!requireNamespace("renv", quietly = TRUE)) {
          install.packages("renv", repos = "https://cloud.r-project.org")
        }
        
        if (file.exists("renv.lock")) {
          # Restore from lockfile
          message("Restoring packages from renv.lock...")
          renv::restore(prompt = FALSE)
        } else {
          # No lockfile, install required packages
          message("No renv.lock found. Installing required packages...")
          
          # Regular CRAN packages
          cran_pkgs <- c("targets", "tarchetypes", "data.table", "ggplot2", "patchwork", 
                         "purrr", "here", "dplyr", "tidyr", "qs", "qs2", "crew", 
                         "primarycensored", "fitdistrplus", "profvis", 
                         "rmarkdown", "knitr", "visNetwork", "htmlwidgets", "webshot2")
          
          # Install CRAN packages
          renv::install(cran_pkgs)
          
          # Install cmdstanr from GitHub (pinned to v0.9.0)
          message("Installing cmdstanr from GitHub (v0.9.0)...")
          renv::install("stan-dev/cmdstanr@v0.9.0")
          
          # Create initial lockfile
          message("Creating renv.lock...")
          renv::snapshot(prompt = FALSE)
        }
        
        # Special handling for cmdstanr - install CmdStan v2.36.0
        if (requireNamespace("cmdstanr", quietly = TRUE)) {
          tryCatch({
            version <- cmdstanr::cmdstan_version()
            message("CmdStan version: ", version)
          }, error = function(e) {
            message("Installing CmdStan v2.36.0...")
            cmdstanr::install_cmdstan(
              version = "2.36.0",
              overwrite = TRUE
            )
            message("CmdStan v2.36.0 installed successfully")
          })
        }
        '
      - echo "✅ Package management complete"

  renv-update:
    desc: Update renv lockfile with current package versions
    cmds:
      - echo "📸 Updating renv lockfile..."
      - Rscript -e "renv::snapshot(prompt = FALSE)"
      - echo "✅ renv.lock updated"

  profile:
    desc: Profile the targets pipeline to identify performance bottlenecks
    cmds:
      - echo "🔍 Profiling targets pipeline..."
      - |
        Rscript -e '
        if (!requireNamespace("profvis", quietly = TRUE)) {
          stop("The profvis package is required. Run: task install-deps")
        }
        
        message("Running pipeline with profiling enabled...")
        message("This may take longer than normal execution.")
        
        # Run profiling
        results <- profvis::profvis(
          targets::tar_make(
            callr_function = NULL,  # Run in current session
            use_crew = FALSE,       # Disable parallel for accurate profiling
            as_job = FALSE          # Run in foreground
          )
        )
        
        # Save results
        saveRDS(results, "profile_results.rds")
        
        # Save HTML report
        htmlwidgets::saveWidget(results, "profile_report.html", selfcontained = TRUE)
        
        message("\n✅ Profiling complete!")
        message("   - Interactive viewer opened in browser")
        message("   - Results saved to: profile_results.rds")
        message("   - HTML report saved to: profile_report.html")
        '

  profile-view:
    desc: View previously saved profiling results
    cmds:
      - echo "📊 Loading profiling results..."
      - |
        Rscript -e '
        if (!file.exists("profile_results.rds")) {
          stop("No profiling results found. Run: task profile")
        }
        
        results <- readRDS("profile_results.rds")
        print(results, aggregate = TRUE)
        message("\n✅ Profile viewer opened in browser")
        '

  manuscript:
    desc: Render the manuscript to PDF and HTML
    deps: [manuscript-html, manuscript-pdf]
    cmds:
      - echo "✅ Manuscript rendered successfully"

  manuscript-pdf:
    desc: Render the manuscript to PDF only
    deps: [check-quarto]
    cmds:
      - echo "📄 Rendering manuscript to PDF..."
      - cd paper && quarto render main.qmd --to pdf
      - echo "✅ PDF rendered at paper/main.pdf"

  manuscript-html:
    desc: Render the manuscript to HTML only
    deps: [check-quarto]
    cmds:
      - echo "📄 Rendering manuscript to HTML..."
      - cd paper && quarto render main.qmd --to html
      - echo "✅ HTML rendered at paper/main.html"

  check-quarto:
    desc: Check if Quarto is installed
    cmds:
      - |
        if ! command -v quarto &> /dev/null; then
          echo "❌ Quarto is not installed"
          echo "📥 Please install Quarto from: https://quarto.org/docs/get-started/"
          echo "   Or use: brew install quarto (macOS)"
          exit 1
        else
          echo "✅ Quarto is installed: $(quarto --version)"
        fi