name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install task
      run: |
        sh -c "$(curl -ssL https://taskfile.dev/install.sh)"
        sudo mv ./bin/task /usr/local/bin/
  
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libsecret-1-dev

    - uses: r-lib/actions/setup-renv@v2

    - name: Lint package
      run: task lint