name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-renv@v2

    - name: Install lintr
      run: |
        Rscript -e "if (!requireNamespace('lintr', quietly = TRUE)) install.packages('lintr')"

    - name: Lint package
      run: |
        Rscript -e "
        library(lintr)
        lints <- lint_package()
        if (length(lints) > 0) {
          cat('=== LINTING ISSUES FOUND ===\n')
          print(lints)
          cat('\n=== Please fix the above issues ===\n')
          quit(status = 1)
        } else {
          cat('✓ Package passed linting checks\n')
          quit(status = 0)
        }
        "