name: Test Parameter Recovery

on:
  pull_request:
    branches: [issue-26-implement-pmf-tools]
  push:
    branches: [issue-26-implement-pmf-tools]
  workflow_dispatch:

jobs:
  test-parameter-recovery:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.0'
        
    - name: Install task
      run: |
        sh -c "$(curl -ssL https://taskfile.dev/install.sh)"
        sudo mv ./bin/task /usr/local/bin/
        
    - name: Install CmdStan
      uses: epinowcast/actions/install-cmdstan@v1
      with:
        cmdstan-version: '2.36.0'
  
    - uses: r-lib/actions/setup-renv@v2
      
    - name: Run test pipeline
      run: task test-run
      
    - name: Check results
      run: |
        Rscript -e "
        library(targets);
        if (!tar_exist('model_fits')) {
          stop('❌ Pipeline failed: model_fits not found')
        }
        results <- tar_read('model_fits');
        cat('✅ Parameter recovery test completed\n');
        cat('Number of results:', nrow(results), '\n');
        cat('Methods tested:', paste(unique(results\$method), collapse=', '), '\n');
        "
      
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          _targets/
          figures/
          data/results/
        retention-days: 7

