name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install CmdStan
        uses: epinowcast/actions/install-cmdstan@v1
        with:
          cmdstan-version: '2.36.0'

      - uses: r-lib/actions/setup-renv@v2

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE
          )
        shell: Rscript {0}